[Variables]
; CPU0 Name
HWiNFO-CPU0-Name-SensorId=0xf0000300
HWiNFO-CPU0-Name-SensorInstance=0x0
; CPU0 Usage
HWiNFO-CPU0-Usage-SensorId=0xf0000300
HWiNFO-CPU0-Usage-SensorInstance=0x0
HWiNFO-CPU0-Usage-EntryId=0xfe
; CPU0 Temp
HWiNFO-CPU0-Temp-SensorId=0xf0000400
HWiNFO-CPU0-Temp-SensorInstance=0x0
HWiNFO-CPU0-Temp-EntryId=0x7f
; CPU0 FAN
HWiNFO-CPU0-Fan-SensorId=0xf000ac00
HWiNFO-CPU0-Fan-SensorInstance=0x0
HWiNFO-CPU0-Fan-EntryId=0xa0
CPU0-Fan-Min=1000
CPU0-Fan-Max=5000




; GPU0 Name
HWiNFO-GPU0-Name-SensorId=0xf0002a00
HWiNFO-GPU0-Name-SensorInstance=0x0
; GPU0 Usage
HWiNFO-GPU0-Usage-SensorId=0xf0002a00
HWiNFO-GPU0-Usage-SensorInstance=0x0
HWiNFO-GPU0-Usage-EntryId=0xe0
; GPU0 Temp
HWiNFO-GPU0-Temp-SensorId=0xf0002a00
HWiNFO-GPU0-Temp-SensorInstance=0x0
HWiNFO-GPU0-Temp-EntryId=0x4
; GPU0 FAN
HWiNFO-GPU0-Fan-SensorId=0xf000ac00
HWiNFO-GPU0-Fan-SensorInstance=0x0
HWiNFO-GPU0-Fan-EntryId=0xa0
GPU0-Fan-Min=1000
GPU0-Fan-Max=5000


; GPU1 Name
HWiNFO-GPU1-Name-SensorId=0xe0002000
HWiNFO-GPU1-Name-SensorInstance=0x14
; GPU1 Usage
HWiNFO-GPU1-Usage-SensorId=0xe0002000
HWiNFO-GPU1-Usage-SensorInstance=0x14
HWiNFO-GPU1-Usage-EntryId=0xe9
; GPU1 Temp
HWiNFO-GPU1-Temp-SensorId=0xe0002000
HWiNFO-GPU1-Temp-SensorInstance=0x14
HWiNFO-GPU1-Temp-EntryId=0x0
; GPU1 FAN
HWiNFO-GPU1-Fan-SensorId=0xf000ac00
HWiNFO-GPU1-Fan-SensorInstance=0x0
HWiNFO-GPU1-Fan-EntryId=0xa0
GPU1-Fan-Min=1000
GPU1-Fan-Max=5000